# Etapa 1: build
FROM node:20 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Generar Prisma si tu microservicio lo usa (sino, puedes omitir esta línea)
# RUN npx prisma generate --schema=src/infrastructure/prisma/schema.prisma

RUN npm run build

# Etapa 2: runtime
FROM node:20 AS runner

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist

ENV NODE_ENV=production
ENV PORT=3002

EXPOSE 3002

CMD ["node", "dist/main.js"]
