version: "3.9"
services:
  auth-usuarios-db:
    image: postgres:16
    container_name: auth-usuarios-db
    environment:
      POSTGRES_USER: mu
      POSTGRES_PASSWORD: mu
      POSTGRES_DB: auth_usuarios_db
    ports:
      - "5432:5432"
    volumes:
      - auth_usuarios_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mu -d auth_usuarios_db"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  auth_usuarios_db_data:
