services:

  # =====================
  # DATABASE: AUTH-USUARIOS
  # =====================
  db-auth:
    image: postgres:16
    environment:
      POSTGRES_USER: mu
      POSTGRES_PASSWORD: mu
      POSTGRES_DB: mercadourbano
    ports:
      - "5432:5432"
    volumes:
      - db_auth_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mu -d mercadourbano"]
      interval: 5s
      timeout: 5s
      retries: 20

  # =====================
  # RabbitMQ
  # =====================
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 10s
      retries: 10

  # =====================
  # AUTH-USUARIOS
  # =====================
  auth-usuarios:
    build:
      context: ./auth-usuarios
      dockerfile: dockerfile
    container_name: auth-usuarios
    env_file:
      - ./auth-usuarios/.env
    environment:
      DATABASE_URL: postgres://mu:mu@db-auth:5432/mercadourbano
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      JWT_SECRET: super-secret-change-me
      NODE_ENV: production
      PORT: "3001"
    depends_on:
      db-auth:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "3001:3001"
    command: >
      sh -c "npx prisma migrate deploy --schema=prisma/schema.prisma &&
             npm run start:prod"

  # =====================
  # NOTIFICACIONES
  # =====================
  notificaciones:
    build: 
      context: ./notificaciones
      dockerfile: dockerfile
    container_name: notificaciones
    env_file:
      - ./notificaciones/.env
    environment:
      NODE_ENV: production
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_started
    ports:
      - "3002:3002"

  # =====================
  # DATABASE: RECOMENDACIONES
  # =====================
  db-recomendaciones:
    image: postgres:16
    environment:
      POSTGRES_USER: mu
      POSTGRES_PASSWORD: mu
      POSTGRES_DB: recomendaciones
    ports:
      - "5433:5432"
    volumes:
      - db_recomendaciones_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mu -d recomendaciones"]
      interval: 5s
      timeout: 5s
      retries: 20

  # =====================
  # API RECOMENDACIONES
  # =====================
  api-recomendaciones:
    build: 
      context: ./recomendaciones
      dockerfile: dockerfile
    env_file:
      - ./recomendaciones/.env
    environment:
      DATABASE_URL: postgres://mu:mu@db-recomendaciones:5432/recomendaciones
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      JWT_SECRET: super-secret-change-me
      PORT: "3001"
    depends_on:
      db-recomendaciones:
        condition: service_healthy
    ports:
      - "3000:3001"
    command: >
      sh -c "npx prisma migrate deploy --schema=prisma/schema.prisma &&
            npm run start:prod"

  # =====================
  # DATABASE: CATALOGO PRODUCTOS
  # =====================
  db-catalogo:
    image: postgres:16
    environment:
      POSTGRES_USER: mu
      POSTGRES_PASSWORD: mu
      POSTGRES_DB: catalogo_productos
    ports:
      - "5434:5432"
    volumes:
      - db_catalogo_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mu -d catalogo_productos"]
      interval: 5s
      timeout: 5s
      retries: 20

  # =====================
  # API CATALOGO PRODUCTOS
  # =====================
  catalogo-productos:
    build: 
      context: ./catalogo-productos
      dockerfile: dockerfile
    ports:
      - "3004:3004"
    env_file:
      - ./catalogo-productos/.env
    environment:
      DATABASE_URL: postgresql://mu:mu@db-catalogo:5432/catalogo_productos
      JWT_SECRET: super-secret-change-me
      PORT: "3004"
    depends_on:
      db-catalogo:
        condition: service_healthy

  # =====================
  # DATABASE: CARRITO
  # =====================
  db-carrito:
    image: postgres:16
    environment:
      POSTGRES_USER: mu
      POSTGRES_PASSWORD: mu
      POSTGRES_DB: carrito
    ports:
      - "5436:5432"
    volumes:
      - db_carrito_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mu -d carrito"]
      interval: 5s
      timeout: 5s
      retries: 20

  # =====================
  # API CARRITO
  # =====================
  carrito:
    build:
      context: ./carrito
      dockerfile: dockerfile
    container_name: carrito
    env_file:
      - ./carrito/.env
    environment:
      DATABASE_URL: postgres://mu:mu@db-carrito:5432/carrito
      USERS_API_URL: http://auth-usuarios:3001
      JWT_SECRET: super-secret-change-me
      PORT: "3005"
    depends_on:
      db-carrito:
        condition: service_healthy
      auth-usuarios:
        condition: service_started
    ports:
      - "3005:3005"
    command: >
      sh -c "npx prisma migrate deploy --schema=prisma/schema.prisma &&
             npm run start:prod"

volumes:
  db_auth_data:
  db_recomendaciones_data:
  db_catalogo_data:
  db_carrito_data:
