# Etapa 1: build
FROM node:20 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Generar Prisma client
RUN npx prisma generate --schema=prisma/schema.prisma
RUN npx prisma migrate --schema=prisma/schema.prisma

# Compilar NestJS a producción
RUN npm run build

# Etapa 2: runtime
FROM node:20 AS runner

WORKDIR /app

# Copiamos solo lo necesario del builder
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/prisma ./prisma

ENV NODE_ENV=production
ENV PORT=3001

EXPOSE 3001

CMD ["node", "dist/main.js"]
