# ---------------------------
# 1. ETAPA DE BUILD
# ---------------------------
FROM node:20 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

RUN npx prisma generate --schema=prisma/schema.prisma
RUN npm run build


# ---------------------------
# 2. ETAPA FINAL
# ---------------------------
FROM node:20 AS runner

WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/node_modules/.prisma ./node_modules/.prisma

ENV PORT=3001

CMD ["node", "dist/main.js"]
