# Imagen base
FROM node:20

# Carpeta de trabajo
WORKDIR /app

# Copiar dependencias e instalarlas
COPY package*.json ./
RUN npm install

# Copiar el resto del código
COPY . .

# Puerto expuesto
EXPOSE 3000

# Comando de arranque
CMD ["npm", "run", "start:dev"]
