FROM node:20 AS builder

WORKDIR /app

COPY package*.json ./
COPY .env .env

RUN npm install
RUN npm install prisma@5.13.0 --save-dev

COPY . .

# Generar prisma client
RUN npx prisma generate --schema=prisma/schema.prisma

RUN npm run build

FROM node:20 AS runner

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/node_modules/.prisma ./node_modules/.prisma

ENV PORT=3005

CMD ["node", "dist/main.js"]
